name: "Gemini AI Code Review Action"
description: "Uses Google Gemini to perform an AI-powered code review on pull requests."
author: "Petar Zarkov"

inputs:
  exclude:
    description: "Comma-separated list of file patterns to exclude from the review (e.g., *.md, dist/*, package-lock.json)."
    required: false
    default: "*.md,*.json,package-lock.json,*.yaml,*.test.ts,migrations/*,*.spec.ts,*.e2e.ts,test/*,tests/*"

  model:
    description: "The model to use for the code review. You can find the list of available models [here](https://ai.google.dev/gemini-api/docs/models)."
    required: false
    default: "gemini-2.5-pro"

  enable_conversation_context:
    description: "Enable conversation context to maintain discussion continuity across multiple PR reviews. When enabled, the AI will remember previous reviews and comments."
    required: false
    default: "true"

  skip_draft_prs:
    description: "Whether to skip code review for draft pull requests. When true, the action will not review draft PRs."
    required: false
    default: "true"

  language:
    description: "The language for AI responses (e.g., 'English', 'Spanish', 'French', 'German', etc.). The AI will provide code review comments in the specified language."
    required: false

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "git-pull-request"
  color: "blue"
